import type { SiteRelationship } from "../types/domain.ts";

export const relationshipSeeds: SiteRelationship[] = [
  {
    fromSlug: "hagia-sophia",
    toSlug: "blue-mosque",
    relationshipType: "paired-visit",
    strength: 0.95,
    notes: "Natural pairing in Sultanahmet for first-time visitors.",
  },
  {
    fromSlug: "hagia-sophia",
    toSlug: "basilica-cistern",
    relationshipType: "nearby",
    strength: 0.95,
  },
  {
    fromSlug: "hagia-sophia",
    toSlug: "hippodrome-of-constantinople",
    relationshipType: "nearby",
    strength: 0.9,
  },
  {
    fromSlug: "hagia-sophia",
    toSlug: "topkapi-palace",
    relationshipType: "paired-visit",
    strength: 0.85,
  },
  {
    fromSlug: "blue-mosque",
    toSlug: "hippodrome-of-constantinople",
    relationshipType: "nearby",
    strength: 0.9,
  },
  {
    fromSlug: "topkapi-palace",
    toSlug: "istanbul-archaeological-museums",
    relationshipType: "paired-visit",
    strength: 0.9,
  },
  {
    fromSlug: "topkapi-palace",
    toSlug: "gulhane-park",
    relationshipType: "nearby",
    strength: 0.8,
  },
  {
    fromSlug: "suleymaniye-mosque",
    toSlug: "grand-bazaar",
    relationshipType: "paired-visit",
    strength: 0.8,
  },
  {
    fromSlug: "grand-bazaar",
    toSlug: "spice-bazaar",
    relationshipType: "same-theme",
    strength: 0.8,
  },
  {
    fromSlug: "spice-bazaar",
    toSlug: "new-mosque",
    relationshipType: "nearby",
    strength: 0.9,
  },
  {
    fromSlug: "new-mosque",
    toSlug: "rustem-pasha-mosque",
    relationshipType: "nearby",
    strength: 0.85,
  },
  {
    fromSlug: "galata-tower",
    toSlug: "istiklal-avenue",
    relationshipType: "paired-visit",
    strength: 0.85,
  },
  {
    fromSlug: "istiklal-avenue",
    toSlug: "cicek-passage",
    relationshipType: "nearby",
    strength: 0.9,
  },
  {
    fromSlug: "istiklal-avenue",
    toSlug: "pera-museum",
    relationshipType: "same-theme",
    strength: 0.7,
  },
  {
    fromSlug: "istiklal-avenue",
    toSlug: "taksim-square",
    relationshipType: "paired-visit",
    strength: 0.95,
  },
  {
    fromSlug: "balat-walking-area",
    toSlug: "fener-walking-area",
    relationshipType: "paired-visit",
    strength: 0.95,
  },
  {
    fromSlug: "fener-walking-area",
    toSlug: "ecumenical-patriarchate",
    relationshipType: "paired-visit",
    strength: 0.9,
  },
  {
    fromSlug: "balat-walking-area",
    toSlug: "bulgarian-st-stephen-church",
    relationshipType: "nearby",
    strength: 0.85,
  },
  {
    fromSlug: "fener-walking-area",
    toSlug: "chora-church",
    relationshipType: "same-theme",
    strength: 0.7,
  },
  {
    fromSlug: "hagia-sophia",
    toSlug: "chora-church",
    relationshipType: "same-theme",
    strength: 0.85,
  },
  {
    fromSlug: "hagia-sophia",
    toSlug: "suleymaniye-mosque",
    relationshipType: "contrast-over-time",
    strength: 0.85,
    notes: "Useful for comparing Byzantine imperial form and Ottoman imperial response.",
  },
  {
    fromSlug: "topkapi-palace",
    toSlug: "dolmabahce-palace",
    relationshipType: "contrast-over-time",
    strength: 0.95,
    notes: "Helps explain the shift from older Ottoman court life to later imperial modernization.",
  },
  {
    fromSlug: "dolmabahce-palace",
    toSlug: "ortakoy-mosque",
    relationshipType: "paired-visit",
    strength: 0.75,
  },
  {
    fromSlug: "ortakoy-mosque",
    toSlug: "rumeli-fortress",
    relationshipType: "nearby",
    strength: 0.65,
  },
];
