import type { Site } from "../types/domain.ts";

export const siteSeeds: Site[] = [
  {
    slug: "hagia-sophia",
    name: "Hagia Sophia",
    city: "istanbul",
    neighborhood: "Sultanahmet",
    latitude: 41.0086,
    longitude: 28.9802,
    shortDescription:
      "A monumental former cathedral and mosque at the center of Istanbul's imperial old city.",
    historicalSignificance:
      "Hagia Sophia captures the layered transformation of Istanbul from Byzantine capital to Ottoman imperial city through religion, architecture, and political symbolism.",
    estimatedVisitMinutes: 75,
    typicalWaitMinutes: 20,
    costCategory: "medium",
    advanceTicketRequired: false,
    mustBookAhead: false,
    openingHoursNote: "Expect heavier security lines during peak daytime hours.",
    indoorOutdoor: "mixed",
    paceIntensity: "medium",
    familiarityLevelHint: "all",
    editorialPriority: 5,
    themes: [
      { slug: "byzantine", weight: 0.95 },
      { slug: "religious-history", weight: 1 },
      { slug: "architecture", weight: 0.85 },
      { slug: "ottoman", weight: 0.6 },
    ],
  },
  {
    slug: "blue-mosque",
    name: "Blue Mosque",
    city: "istanbul",
    neighborhood: "Sultanahmet",
    latitude: 41.0054,
    longitude: 28.9768,
    shortDescription:
      "One of the defining imperial mosques of Ottoman Istanbul, facing Hagia Sophia across the historic core.",
    historicalSignificance:
      "The Blue Mosque represents Ottoman imperial ambition, religious patronage, and the visual dialogue between Ottoman and Byzantine monumental architecture.",
    estimatedVisitMinutes: 45,
    typicalWaitMinutes: 15,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    openingHoursNote: "Tourist access is limited around prayer times.",
    indoorOutdoor: "mixed",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 5,
    themes: [
      { slug: "ottoman", weight: 0.95 },
      { slug: "religious-history", weight: 0.9 },
      { slug: "architecture", weight: 0.85 },
    ],
  },
  {
    slug: "basilica-cistern",
    name: "Basilica Cistern",
    city: "istanbul",
    neighborhood: "Sultanahmet",
    latitude: 41.0084,
    longitude: 28.9779,
    shortDescription:
      "A vast Byzantine underground water reservoir beneath the old imperial center.",
    historicalSignificance:
      "The Basilica Cistern shows the infrastructural sophistication of Byzantine Constantinople and adds a material layer to understanding how the capital sustained itself.",
    estimatedVisitMinutes: 45,
    typicalWaitMinutes: 25,
    costCategory: "medium",
    advanceTicketRequired: true,
    mustBookAhead: true,
    recommendedBookingNotes: "Advance tickets are recommended during peak season.",
    indoorOutdoor: "indoor",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 5,
    themes: [
      { slug: "byzantine", weight: 0.9 },
      { slug: "architecture", weight: 0.7 },
    ],
  },
  {
    slug: "topkapi-palace",
    name: "Topkapi Palace",
    city: "istanbul",
    neighborhood: "Sultanahmet",
    latitude: 41.0115,
    longitude: 28.9833,
    shortDescription:
      "The principal palace of the Ottoman sultans overlooking the Bosporus and Golden Horn.",
    historicalSignificance:
      "Topkapi Palace embodies Ottoman imperial administration, dynastic life, court culture, and the geographic strategy of ruling from the old Byzantine center.",
    estimatedVisitMinutes: 150,
    typicalWaitMinutes: 30,
    costCategory: "high",
    advanceTicketRequired: true,
    mustBookAhead: true,
    recommendedBookingNotes: "Advance ticket purchase is highly recommended.",
    openingHoursNote: "Large complex; allocate extra time for treasury and harem sections.",
    indoorOutdoor: "mixed",
    paceIntensity: "high",
    familiarityLevelHint: "all",
    editorialPriority: 5,
    themes: [
      { slug: "ottoman", weight: 1 },
      { slug: "architecture", weight: 0.7 },
      { slug: "religious-history", weight: 0.35 },
    ],
  },
  {
    slug: "hippodrome-of-constantinople",
    name: "Hippodrome of Constantinople",
    city: "istanbul",
    neighborhood: "Sultanahmet",
    latitude: 41.0065,
    longitude: 28.9784,
    shortDescription:
      "The former ceremonial and sporting heart of Byzantine Constantinople, now read through surviving monuments and public space.",
    historicalSignificance:
      "The Hippodrome helps explain imperial spectacle, public life, and the spatial organization of the Byzantine capital at the core of modern Sultanahmet.",
    estimatedVisitMinutes: 25,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "outdoor",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 4,
    themes: [
      { slug: "byzantine", weight: 0.95 },
      { slug: "architecture", weight: 0.35 },
    ],
  },
  {
    slug: "little-hagia-sophia",
    name: "Little Hagia Sophia",
    city: "istanbul",
    neighborhood: "Sultanahmet",
    latitude: 41.0037,
    longitude: 28.9726,
    shortDescription:
      "A smaller former Byzantine church converted into a mosque, tucked into the old city south of the main imperial monuments.",
    historicalSignificance:
      "Little Hagia Sophia provides a more intimate window into Byzantine church architecture and later Ottoman religious reuse outside the most iconic tourist axis.",
    estimatedVisitMinutes: 30,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "mixed",
    paceIntensity: "low",
    familiarityLevelHint: "enthusiast",
    editorialPriority: 3,
    themes: [
      { slug: "byzantine", weight: 0.85 },
      { slug: "religious-history", weight: 0.9 },
      { slug: "architecture", weight: 0.65 },
      { slug: "ottoman", weight: 0.35 },
    ],
  },
  {
    slug: "suleymaniye-mosque",
    name: "Suleymaniye Mosque",
    city: "istanbul",
    neighborhood: "Eminonu",
    latitude: 41.0162,
    longitude: 28.9637,
    shortDescription:
      "A commanding imperial mosque complex designed by Sinan on one of the city's most prominent ridges.",
    historicalSignificance:
      "The Suleymaniye Mosque is one of the clearest architectural statements of Ottoman imperial confidence and an essential site for understanding religious, political, and urban history together.",
    estimatedVisitMinutes: 60,
    typicalWaitMinutes: 5,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "mixed",
    paceIntensity: "medium",
    familiarityLevelHint: "all",
    editorialPriority: 5,
    themes: [
      { slug: "ottoman", weight: 1 },
      { slug: "religious-history", weight: 0.9 },
      { slug: "architecture", weight: 0.95 },
    ],
  },
  {
    slug: "grand-bazaar",
    name: "Grand Bazaar",
    city: "istanbul",
    neighborhood: "Beyazit",
    latitude: 41.0107,
    longitude: 28.9681,
    shortDescription:
      "A historic commercial complex that reflects the scale and texture of Ottoman urban life.",
    historicalSignificance:
      "The Grand Bazaar is valuable not just as a market but as a long-lived urban institution that helps explain commerce, craft, and the social geography of Ottoman Istanbul.",
    estimatedVisitMinutes: 60,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "indoor",
    paceIntensity: "medium",
    familiarityLevelHint: "all",
    editorialPriority: 4,
    themes: [
      { slug: "ottoman", weight: 0.85 },
      { slug: "neighborhood-change", weight: 0.55 },
      { slug: "architecture", weight: 0.3 },
    ],
  },
  {
    slug: "galata-tower",
    name: "Galata Tower",
    city: "istanbul",
    neighborhood: "Galata",
    latitude: 41.0256,
    longitude: 28.9741,
    shortDescription:
      "A landmark tower above Galata that helps situate the city spatially and historically.",
    historicalSignificance:
      "Galata Tower anchors the story of Istanbul beyond the old imperial core and helps connect architecture, trade districts, and neighborhood transformation over time.",
    estimatedVisitMinutes: 45,
    typicalWaitMinutes: 20,
    costCategory: "medium",
    advanceTicketRequired: true,
    mustBookAhead: false,
    openingHoursNote: "Views are best earlier or later in the day to avoid peak lines.",
    indoorOutdoor: "mixed",
    paceIntensity: "medium",
    familiarityLevelHint: "all",
    editorialPriority: 5,
    themes: [
      { slug: "architecture", weight: 0.8 },
      { slug: "neighborhood-change", weight: 0.7 },
      { slug: "ottoman", weight: 0.4 },
      { slug: "byzantine", weight: 0.25 },
    ],
  },
  {
    slug: "istiklal-avenue",
    name: "Istiklal Avenue",
    city: "istanbul",
    neighborhood: "Beyoglu",
    latitude: 41.0339,
    longitude: 28.9778,
    shortDescription:
      "A major pedestrian spine through Beyoglu that reveals the social and political evolution of modern Istanbul.",
    historicalSignificance:
      "Istiklal Avenue is useful for understanding late Ottoman cosmopolitan life, republican transformation, urban memory, and how central neighborhoods changed over time.",
    estimatedVisitMinutes: 75,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "outdoor",
    paceIntensity: "medium",
    familiarityLevelHint: "all",
    editorialPriority: 4,
    themes: [
      { slug: "neighborhood-change", weight: 0.95 },
      { slug: "modern-political-history", weight: 0.7 },
      { slug: "architecture", weight: 0.5 },
    ],
  },
  {
    slug: "taksim-square",
    name: "Taksim Square",
    city: "istanbul",
    neighborhood: "Beyoglu",
    latitude: 41.0369,
    longitude: 28.985,
    shortDescription:
      "A major public square that plays an outsized role in the political memory of modern Istanbul.",
    historicalSignificance:
      "Taksim Square is one of the clearest sites for reading republican symbolism, protest culture, and the politics of public space in modern Istanbul.",
    estimatedVisitMinutes: 25,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "outdoor",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 4,
    themes: [
      { slug: "modern-political-history", weight: 1 },
      { slug: "neighborhood-change", weight: 0.75 },
    ],
  },
  {
    slug: "balat-walking-area",
    name: "Balat Walking Area",
    city: "istanbul",
    neighborhood: "Balat",
    latitude: 41.0293,
    longitude: 28.9498,
    shortDescription:
      "A historically layered district whose streets help tell stories of migration, minority life, and urban change.",
    historicalSignificance:
      "Balat is valuable because it reveals long-term neighborhood transformation through the built environment, communal memory, and the coexistence of different historical layers.",
    estimatedVisitMinutes: 90,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "outdoor",
    paceIntensity: "medium",
    familiarityLevelHint: "enthusiast",
    editorialPriority: 4,
    themes: [
      { slug: "neighborhood-change", weight: 1 },
      { slug: "religious-history", weight: 0.55 },
      { slug: "architecture", weight: 0.45 },
    ],
  },
  {
    slug: "fener-walking-area",
    name: "Fener Walking Area",
    city: "istanbul",
    neighborhood: "Fener",
    latitude: 41.0299,
    longitude: 28.9525,
    shortDescription:
      "A district associated with religious institutions, minority communities, and layered urban continuity.",
    historicalSignificance:
      "Fener helps travelers understand how religious institutions, community identity, and neighborhood evolution intersect in Istanbul beyond the standard tourist core.",
    estimatedVisitMinutes: 75,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "outdoor",
    paceIntensity: "medium",
    familiarityLevelHint: "enthusiast",
    editorialPriority: 4,
    themes: [
      { slug: "neighborhood-change", weight: 0.95 },
      { slug: "religious-history", weight: 0.75 },
      { slug: "architecture", weight: 0.45 },
    ],
  },
  {
    slug: "ecumenical-patriarchate",
    name: "Ecumenical Patriarchate of Constantinople",
    city: "istanbul",
    neighborhood: "Fener",
    latitude: 41.0295,
    longitude: 28.9519,
    shortDescription:
      "A major center of Eastern Orthodox religious history located within the Fener district.",
    historicalSignificance:
      "The Patriarchate is a key site for understanding continuity and transformation in Christian institutional life after the fall of Constantinople.",
    estimatedVisitMinutes: 40,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "indoor",
    paceIntensity: "low",
    familiarityLevelHint: "enthusiast",
    editorialPriority: 4,
    themes: [
      { slug: "religious-history", weight: 1 },
      { slug: "byzantine", weight: 0.65 },
      { slug: "neighborhood-change", weight: 0.45 },
    ],
  },
  {
    slug: "bulgarian-st-stephen-church",
    name: "Bulgarian St. Stephen Church",
    city: "istanbul",
    neighborhood: "Balat",
    latitude: 41.0273,
    longitude: 28.9491,
    shortDescription:
      "A distinctive church on the Golden Horn tied to minority religious history and neighborhood identity.",
    historicalSignificance:
      "The church adds depth to itineraries focused on minority communities, religious plurality, and the changing urban fabric of the Golden Horn districts.",
    estimatedVisitMinutes: 30,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "mixed",
    paceIntensity: "low",
    familiarityLevelHint: "enthusiast",
    editorialPriority: 3,
    themes: [
      { slug: "religious-history", weight: 0.85 },
      { slug: "architecture", weight: 0.75 },
      { slug: "neighborhood-change", weight: 0.45 },
    ],
  },
  {
    slug: "chora-church",
    name: "Chora Church",
    city: "istanbul",
    neighborhood: "Edirnekapi",
    latitude: 41.0317,
    longitude: 28.9392,
    shortDescription:
      "A major Byzantine monument beyond the main tourist core, known for its artistic and architectural significance.",
    historicalSignificance:
      "Chora Church is one of the strongest sites for understanding late Byzantine artistic achievement and provides important depth beyond Hagia Sophia in the Byzantine story.",
    estimatedVisitMinutes: 60,
    typicalWaitMinutes: 15,
    costCategory: "medium",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "indoor",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 5,
    themes: [
      { slug: "byzantine", weight: 1 },
      { slug: "religious-history", weight: 0.9 },
      { slug: "architecture", weight: 0.85 },
    ],
  },
  {
    slug: "istanbul-archaeological-museums",
    name: "Istanbul Archaeological Museums",
    city: "istanbul",
    neighborhood: "Sultanahmet",
    latitude: 41.0117,
    longitude: 28.9813,
    shortDescription:
      "A museum complex near Topkapi that broadens itineraries beyond monuments into the city's longer imperial context.",
    historicalSignificance:
      "The museums help connect Byzantine and Ottoman Istanbul to wider imperial collecting, archaeology, and the politics of heritage.",
    estimatedVisitMinutes: 75,
    typicalWaitMinutes: 10,
    costCategory: "medium",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "indoor",
    paceIntensity: "medium",
    familiarityLevelHint: "all",
    editorialPriority: 3,
    themes: [
      { slug: "byzantine", weight: 0.4 },
      { slug: "ottoman", weight: 0.45 },
      { slug: "architecture", weight: 0.35 },
    ],
  },
  {
    slug: "gulhane-park",
    name: "Gulhane Park",
    city: "istanbul",
    neighborhood: "Sultanahmet",
    latitude: 41.0132,
    longitude: 28.9819,
    shortDescription:
      "A historic park beside Topkapi that can soften dense old-city itineraries.",
    historicalSignificance:
      "Gulhane Park adds context to the Ottoman palace zone and helps explain how imperial landscapes and public space evolved.",
    estimatedVisitMinutes: 30,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "outdoor",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 2,
    themes: [
      { slug: "ottoman", weight: 0.45 },
      { slug: "neighborhood-change", weight: 0.4 },
    ],
  },
  {
    slug: "spice-bazaar",
    name: "Spice Bazaar",
    city: "istanbul",
    neighborhood: "Eminonu",
    latitude: 41.0165,
    longitude: 28.9702,
    shortDescription:
      "A historic market building that adds commercial and urban texture to Ottoman-centered itineraries.",
    historicalSignificance:
      "The Spice Bazaar helps explain commerce, trade, and the dense urban life of Ottoman Istanbul near the waterfront and mosque complexes.",
    estimatedVisitMinutes: 35,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "indoor",
    paceIntensity: "medium",
    familiarityLevelHint: "all",
    editorialPriority: 3,
    themes: [
      { slug: "ottoman", weight: 0.8 },
      { slug: "neighborhood-change", weight: 0.45 },
    ],
  },
  {
    slug: "rustem-pasha-mosque",
    name: "Rustem Pasha Mosque",
    city: "istanbul",
    neighborhood: "Eminonu",
    latitude: 41.0161,
    longitude: 28.9687,
    shortDescription:
      "A smaller but architecturally rich Ottoman mosque that pairs well with market and waterfront itineraries.",
    historicalSignificance:
      "Rustem Pasha Mosque helps balance major imperial sites with a more focused example of Ottoman religious architecture and urban placement.",
    estimatedVisitMinutes: 25,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "mixed",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 3,
    themes: [
      { slug: "ottoman", weight: 0.85 },
      { slug: "religious-history", weight: 0.7 },
      { slug: "architecture", weight: 0.8 },
    ],
  },
  {
    slug: "new-mosque",
    name: "New Mosque",
    city: "istanbul",
    neighborhood: "Eminonu",
    latitude: 41.0175,
    longitude: 28.9708,
    shortDescription:
      "A major waterfront mosque at Eminonu that helps anchor the commercial and ceremonial edge of the old city.",
    historicalSignificance:
      "The New Mosque is useful for understanding Ottoman religious patronage and how monumental architecture shaped the waterfront approach to the historic core.",
    estimatedVisitMinutes: 35,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "mixed",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 3,
    themes: [
      { slug: "ottoman", weight: 0.85 },
      { slug: "religious-history", weight: 0.75 },
      { slug: "architecture", weight: 0.7 },
    ],
  },
  {
    slug: "pera-museum",
    name: "Pera Museum",
    city: "istanbul",
    neighborhood: "Beyoglu",
    latitude: 41.0318,
    longitude: 28.9759,
    shortDescription:
      "A museum stop in Beyoglu that adds modern cultural and neighborhood context to itineraries west of the Golden Horn.",
    historicalSignificance:
      "Pera Museum supports the story of late Ottoman and modern Beyoglu as a district shaped by cultural exchange and changing urban identity.",
    estimatedVisitMinutes: 60,
    typicalWaitMinutes: 5,
    costCategory: "medium",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "indoor",
    paceIntensity: "low",
    familiarityLevelHint: "enthusiast",
    editorialPriority: 2,
    themes: [
      { slug: "modern-political-history", weight: 0.45 },
      { slug: "neighborhood-change", weight: 0.35 },
      { slug: "architecture", weight: 0.3 },
    ],
  },
  {
    slug: "cicek-passage",
    name: "Cicek Passage",
    city: "istanbul",
    neighborhood: "Beyoglu",
    latitude: 41.0331,
    longitude: 28.9783,
    shortDescription:
      "A small but evocative arcade off Istiklal that adds texture to neighborhood-change itineraries.",
    historicalSignificance:
      "Cicek Passage helps explain the layered commercial and social history of Beyoglu beyond its biggest landmarks.",
    estimatedVisitMinutes: 20,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "mixed",
    paceIntensity: "low",
    familiarityLevelHint: "enthusiast",
    editorialPriority: 2,
    themes: [
      { slug: "neighborhood-change", weight: 0.7 },
      { slug: "architecture", weight: 0.4 },
    ],
  },
  {
    slug: "dolmabahce-palace",
    name: "Dolmabahce Palace",
    city: "istanbul",
    neighborhood: "Besiktas",
    latitude: 41.0392,
    longitude: 29.0007,
    shortDescription:
      "A later Ottoman palace on the Bosporus that broadens itineraries beyond the old imperial core.",
    historicalSignificance:
      "Dolmabahce Palace is a key site for understanding later Ottoman statecraft, changing court aesthetics, and the shift from Topkapi's older imperial model.",
    estimatedVisitMinutes: 120,
    typicalWaitMinutes: 25,
    costCategory: "high",
    advanceTicketRequired: true,
    mustBookAhead: true,
    recommendedBookingNotes: "Reserve tickets ahead for tighter itineraries.",
    indoorOutdoor: "mixed",
    paceIntensity: "medium",
    familiarityLevelHint: "all",
    editorialPriority: 5,
    themes: [
      { slug: "ottoman", weight: 0.9 },
      { slug: "architecture", weight: 0.8 },
      { slug: "modern-political-history", weight: 0.55 },
    ],
  },
  {
    slug: "ortakoy-mosque",
    name: "Ortakoy Mosque",
    city: "istanbul",
    neighborhood: "Ortakoy",
    latitude: 41.0472,
    longitude: 29.0269,
    shortDescription:
      "A Bosporus-side mosque that works well as a later Ottoman supporting stop.",
    historicalSignificance:
      "Ortakoy Mosque helps extend Ottoman architectural itineraries into the Bosporus shoreline and shows how monumental form adapted to waterfront settings.",
    estimatedVisitMinutes: 25,
    typicalWaitMinutes: 0,
    costCategory: "free",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "mixed",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 3,
    themes: [
      { slug: "ottoman", weight: 0.8 },
      { slug: "religious-history", weight: 0.75 },
      { slug: "architecture", weight: 0.7 },
    ],
  },
  {
    slug: "rumeli-fortress",
    name: "Rumeli Fortress",
    city: "istanbul",
    neighborhood: "Sariyer",
    latitude: 41.0849,
    longitude: 29.0568,
    shortDescription:
      "A strategic fortress on the Bosporus that can anchor a more specialized Ottoman itinerary.",
    historicalSignificance:
      "Rumeli Fortress is useful for understanding conquest, military geography, and Ottoman control of the Bosporus before the fall of Constantinople.",
    estimatedVisitMinutes: 60,
    typicalWaitMinutes: 5,
    costCategory: "medium",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "outdoor",
    paceIntensity: "medium",
    familiarityLevelHint: "enthusiast",
    editorialPriority: 3,
    themes: [
      { slug: "ottoman", weight: 0.9 },
      { slug: "architecture", weight: 0.55 },
    ],
  },
  {
    slug: "museum-of-turkish-and-islamic-arts",
    name: "Museum of Turkish and Islamic Arts",
    city: "istanbul",
    neighborhood: "Sultanahmet",
    latitude: 41.0069,
    longitude: 28.9787,
    shortDescription:
      "A museum stop that deepens religious and Ottoman-themed itineraries near the Hippodrome.",
    historicalSignificance:
      "This museum gives historical texture to Ottoman and Islamic material culture while fitting naturally into the Sultanahmet cluster.",
    estimatedVisitMinutes: 60,
    typicalWaitMinutes: 5,
    costCategory: "medium",
    advanceTicketRequired: false,
    mustBookAhead: false,
    indoorOutdoor: "indoor",
    paceIntensity: "low",
    familiarityLevelHint: "all",
    editorialPriority: 3,
    themes: [
      { slug: "ottoman", weight: 0.65 },
      { slug: "religious-history", weight: 0.7 },
      { slug: "architecture", weight: 0.35 },
    ],
  },
];
